name: reflection
author: Andrew Mezoni <andrew.mezoni@gmail.com>
version: 0.0.1
homepage: https://github.com/mezoni/reflection
description: The reflection helper classes over the mirrors based reflection.
